### ISSUE TITLE
Pre-Work

### ISSUE THREAD

**Issue by brianburridge** [cato-hga/Assignments#1]
_This assignment is due on Jan 26, 2015._
## Expectations
- [x] Please read this [Welcome](https://github.com/theironyard-tampabay/Jan2015/blob/master/README.md) to the Iron Yard.
- [x] Please read through these [Expectations](https://github.com/theironyard-tampabay/Jan2015/blob/master/Expectations.md)
## Mind Set

The following resources will help you better understand your current mindset and how the learning process works. I firmly believe, "Failure is not the opposite of success, it's part of success."
- [x] Read this article on [Fixed vs. Growth: The Two Basic Mindsets That Shape Our Lives](http://www.brainpickings.org/2014/01/29/carol-dweck-mindset/)
- [x] Watch the TED talk, [Growing A Talent Hotbed](https://www.youtube.com/watch?v=Aq0pHpNy6bs), by Dan Coyle. Coyle wrote a fantastic book on how our brains learn, called _The Talent Code_. I will refer to it and the philosophy within frequently throughout the class.
## Send me an email with the following
- [x] Which mindset, from the article above, do you most associate with and why?
- [x] What challenges do you think you will face in completing this course and why?
- [x] What distractions are you likely to have during the class that might make it hard for you to handle the work load?
## Development Environment Setup
- [x] Sign up for GitHub and send me your GitHub username
- [x] Make sure to add a profile picture on your GitHub account and your full name, since this will help me learn your name.
- [x] Use installrails.com to install Xcode (note, current version is 6.1.1), Homebrew, git before the class. Stop after Git. Do NOT install RVM and Ruby or anything else.
- [x] Install [Atom](https://atom.io)
- [x] Install Atom shell commands: (Inside Atom, click 'Atom' in upper left, then click on 'Install Shell Commands')
## Read these articles
- [x] [Welcome to Ruby on Rails](http://brianburridge.com/2007/07/25/welcome-to-ruby-on-rails/)
- [x] [Rails Terms and Concepts](http://brianburridge.com/2007/08/09/rails-terms-and-concepts/)
- [x] [The Beginner Mind](http://brianburridge.com/2007/02/07/the-beginner-mind/)
## Hour of Code

Do this no matter what your experience level. It's fun. I did it with my kids last year. They loved it and I actually enjoyed it myself. It's only an hour. Watch the videos as well. They really did a great job of explaining programming paradigms.
- [x] Do the [Hour of Code](http://hourofcode.com/)
## Using a Mac

As you know, we use Macs for all development. I would guess that about 99% of all Rails developers use Macs. It's a much easier platform for this type of development. If you aren't familiar with using a Mac, please go through the tutorials below.
- [x] [Finder Basics](http://support.apple.com/kb/VI209?viewlocale=en_US)
- [x] [Anatomy of a Mac](http://support.apple.com/kb/VI53?viewlocale=en_US)
- [x] [How to use Mac Terminal](https://www.youtube.com/watch?v=I65C4ZXK4ek)
## Understanding the Command line (from Treehouse)

The console is where you will do much of your work. It's crucial to understand it and become comfortable in it. If you haven't used it before, this will definitely be a learning curve. Reading and working through the resources below will help you to be better prepared for day one.
- [x] Read [Command Line Basics](http://blog.teamtreehouse.com/command-line-basics)
- [x] Do [Getting Started with the Console](http://teamtreehouse.com/library/console-foundations-2#getting-started-with-the-console)
- [x] Do [Environment and Redirection](http://teamtreehouse.com/library/console-foundations-2#environment-and-redirection)
- [x] Work through [CommandLine from SkillCrush](http://skillcrush.com/2012/12/03/command-line-2/)
- [x] Read Lifehacker's [A Command Line Primer for Beginners](http://lifehacker.com/5633909/who-needs-a-mouse-learn-to-use-the-command-line-for-almost-anything)
- [x] Read [Command Line Crash course](http://cli.learncodethehardway.org/book/)
## Git

We will be using Git for all source control. This tutorial will help you understand how Git works. We will cover Git and GitHub from the very first day in class.
- [x] Work through the online [TryGit](https://try.github.io/) tutorial.
## HTML/CSS

HTML and CSS are fundamental technologies necessary for all web developers. The tutorial below will give you an introduction to these technologies.
- [x] Complete the [Dash course](https://dash.generalassemb.ly/), which covers HTML, CSS, and very basic JavaScript. This should take you approximately 8-15 hours, depending on your prior experience.
## Typing

Of course, typing is a huge part of being a web developer, because it's how you communicate with the computer. If you are not a proficient touch typists please do the first tutorial below. The second tutorial is a good one for practicing typing some of the commands and more unusual characters used in development.
- [x] Do this [Touch Typing tutorial](http://www.keybr.com/#!game)
- [x] Do this [Typing Practice for Programmers](https://typing.io/), particularly the Ruby on Rails section

*Note: Treehouse requires a monthly subscription of $25/mo but there is a 14 day free trial you can use for the prep work.

**Note: Be sure, if you are reading this via an email notification, that you click through to visit this issue on the site. You can check the checkboxes right on GitHub.com to show your progress, or leave questions in the comments

**Comment by cato-hga** [comment]
Hello Brian,

I just want to make sure I’m doing this correctly. Should I already have some Pre- Work to work on because I don’t see it in my Github. Sorry, I’m pretty knew to Github so I’m a little bit confused.

**Comment by brianburridge** [comment]
Nope, not yet. Will be coming today or tomorrow right here.
