### ISSUE TITLE
A Guessing Game

### ISSUE THREAD

**Issue by brianburridge** [cato-hga/Assignments#13]
_This is assignment 13 and is due on Feb 02, 2015._
- Create a guessing game
- The user must guess the number chosen by the app
- Provide feedback to the user as to if their guess is lower or higher than the number
- Count the number of guesses and output at the end

**Comment by brianburridge** [comment]
Hey @cato-hga 

This is working, but just a reminder, when having the user do something like guess a number within a range, tell them what range the number can be within. Without looking at the code, I wouldn't have known if it was 1 to 7, 1 to 10, or 1 to 1000. :smile:

**Comment by cato-hga** [comment]
Oops! That would be helpful wouldn't it? lol. Sorry about that and thanks for the tip.

**Comment by brianburridge** [comment]
:+1:
