### ISSUE TITLE
Classy Pig Latin

### ISSUE THREAD

**Issue by brianburridge** [cato-hga/Assignments#14]
_This is assignment 14 and is due on Feb 02, 2015._
- Using the structure of a class as I've laid out in this [gist](https://gist.github.com/brianburridge/7e98d358dee03c6b6060), finishing creating the PigLatin class to translate a word into pig latin
- Bonus: modify the app to convert an entire phrase (one word at a time)
- Note the pig latin rules in the comment of the skeleton app

**Comment by cato-hga** [comment]
https://github.com/cato-hga/Assignments/blob/master/assignment14.rb

**Comment by brianburridge** [comment]
:+1:
