### ISSUE TITLE
Movie Querying script

### ISSUE THREAD

**Issue by brianburridge** [cato-hga/Assignments#18]
_This is assignment 18 and is due on Feb 04, 2015._
- http://developer.rottentomatoes.com/
- Use Rotten Tomato's movie querying script to create a command line app which prompts the user for a movie title
- Using the entered movie title, search via the API for the movie's synopsis and output to the user
- If more than one movie comes back, show all the movie title matches with their synopsis

**Comment by cato-hga** [comment]
https://github.com/cato-hga/Assignments/blob/master/assignment18.rb

**Comment by brianburridge** [comment]
This works. Just a few tips to make it better.
1. It's best not to have spaces between your methods and your arguments as you do on line 29 after `get`
2. It seems strange to me that when the user says _goodbye_ to end, that you do a movie search on that term first. I would think when they are done, you'd want to stop before looking that up as a movie title.
3. Check that Ruby Style guide, but indentations should be two spaces. Also, your code within the loop block should all be indented. This will make your code much easier to read.

**Comment by brianburridge** [comment]
Awesome :exclamation: :exclamation:
