### ISSUE TITLE
Hiring and Firing Employees

### ISSUE THREAD

**Issue by brianburridge** [cato-hga/Assignments#24]
_This is assignment 24 and is due on Feb 09, 2015._
- Take the Employee and Company classes, and create functionality to allow the company to hire and fire an employee.
- Create a Ruby app that will use those classes to do the following:
- prompt the user to enter information for the company.
- prompt the user to enter each employee. It will then "hire" each of them.
- show a list of employees, with ids, then ask the user if they would like to fire an employee by entering that id.
- fire the employee by id and show an updated list with that employee no longer in it.

**Comment by cato-hga** [comment]
completed

**Comment by cato-hga** [comment]
https://github.com/cato-hga/Assignments/tree/master/assignment24

**Comment by brianburridge** [comment]
Looks great :exclamation:
