### ISSUE TITLE
More work with classes, getters and setters (in class, pairing)

### ISSUE THREAD

**Issue by brianburridge** [cato-hga/Assignments#26]
_This is assignment 25b and is due on Feb 10, 2015._
- Design and code a Blog and Post class.
- These classes should model a system where a user can create a blog, which will have posts.
- A Blog can have a name, a user_name, and the collection of posts
- A Post can have a name, a summary, the body of the post, the published date, and a word count.
- Since both a blog and a post MUST have a name, override the initializer so that when an object of either class is created, a name must be supplied.

**Comment by brianburridge** [comment]
Talked to you in person about the 5th requirement (the initializers).

**Comment by cato-hga** [comment]
https://github.com/cato-hga/Assignments/tree/master/assignment25b

**Comment by brianburridge** [comment]
@cato-hga 
On lines 18 and 26 of your main.rb, passing an empty string kind of defeats the point here. It would be better to not create those objects until you have the names to pass them. You could prompt the user for the name first, then create the object. I'm going to close this out, but would be good for you to make this change when you have a minute.
