### ISSUE TITLE
Improve the Movie Query app

### ISSUE THREAD

**Issue by brianburridge** [cato-hga/Assignments#31]
_This is assignment 30 and is due on Feb 16, 2015._
- Alter your existing app so you are no longer returning the synopsis in an instance variable, but instead returning the entire first movie result. We will assume for this exercise that the first movie that comes back is the one we want.
- Using all the information returned for the movie, recreate a movie information page like this one on [IMBD]() or this one on [Rotten Tomatoes](http://www.rottentomatoes.com/m/kingsman_the_secret_service/). Note it does not have to have their branding but should nicely layout as much of the movie information as possible. Ex: poster, ratings, synopsis, tomatometer, some cast, running time, etc.
- The goal is to create your own movie information page as though you were creating one for a client's movie app.

**Comment by cato-hga** [comment]
https://github.com/cato-hga/Assignments/tree/master/movie_query

**Comment by brianburridge** [comment]
:+1:
