### ISSUE TITLE
Validations and Associations

### ISSUE THREAD

**Issue by brianburridge** [cato-hga/Assignments#35]
_This is assignment 34 and is due on Feb 19, 2015._
- [Read Active Record Validations](http://guides.rubyonrails.org/active_record_validations.html)
- [Read Active Record Associations](http://guides.rubyonrails.org/association_basics.html)
- Continuing with your app from assignment 33, add a second model (use the migration generator) and use a _reference_ and _belongs_to/has_many_ relationship.
- Also add at least three validations between the two models.
- Test your model relationships in the rails console to be sure they work.

**Comment by cato-hga** [comment]
https://github.com/cato-hga/Assignments/tree/master/scaffold

**Comment by cato-hga** [comment]
https://github.com/cato-hga/Assignments/tree/master/scaffold

**Comment by brianburridge** [comment]
@cato-hga 

The belongs_to relationship isn't setup correctly here. The foreign key should always be named the model name (here it's `company`) and then `_id`. So it would be `company_id`.

When you add the belongs_to, as you've correctly done in the Beer model, rails sees what model you say it belongs to, and then looks for a correctly named foreign key. In this case, although you have the belongs_to setup correctly, Rails is unable to find the appropriate foreign key because you named it the pural of company.

Review the [guide](http://guides.rubyonrails.org/association_basics.html#the-belongs-to-association) on the belongs_to. See if that helps.

**Comment by cato-hga** [comment]
https://github.com/cato-hga/Assignments/tree/master/scaffold

**Comment by brianburridge** [comment]
@cato-hga note, to fix when you have a minute: on _has_many_ associations, they should be plural. As in:

```
    has_many :beers
```

That helps us know it's a collection of many beers.

Other than that, this is all set. I'll close this but when you have a chance, make that one change.
