### ISSUE TITLE
Adding a User model and scoping your app to the current user

### ISSUE THREAD

**Issue by brianburridge** [cato-hga/Assignments#40]
_This is assignment 39 and is due on Feb 26, 2015._
- Modify the app from assignment 36-38, to have a User model
- Also, modify any models that should be scoped to a User, to belong to a user object
- Only show the user's records when in that context
- Create a User guest record in the seed file
- Default your app to always use that User
- Modify at least one model's create to be automatically associated with that User when it's created.
- Deploy to Heroku
- Paste the link to your Heroku app in a comment here for my review

**Comment by cato-hga** [comment]
https://github.com/cato-hga/Theater-App

**Comment by cato-hga** [comment]
https://thawing-sierra-1479.herokuapp.com/

**Comment by cato-hga** [comment]
"Modify at least one model's create to be automatically associated with that User when it's created."

I'm honestly not sure if I even completed that part. I wasn't 100 percent sure of what you were asking for. Please let me know if it's missing. Thanks!

**Comment by brianburridge** [comment]
As we discussed, you covered all the bullets above except for 3rd and 6th one. To do that, using your models, you'll need to provide a way for the user to mark that they've seen a movie. This would be one action that creates your Viewer object.

Then, there should be a link for the user to view all the movies they've seen, using those viewer objects.

**Comment by brianburridge** [comment]
John demonstrated the skills and knowledge for this assignment in his final project.
