### ISSUE TITLE
Debugging a Rails Application

### ISSUE THREAD

**Issue by brianburridge** [cato-hga/Assignments#49]
_This is assignment 48 and is due on Mar 11, 2015._
- Read about ri [Up and Running With Ruby Interactive](http://samuelmullen.com/2012/01/up-and-running-with-ruby-interactive-ri/), [5 Reasons You Should Use ri To Read Ruby Documentation](http://www.jstorimer.com/blogs/workingwithcode/7766081-5-reasons-you-should-use-ri-to-read-ruby-documentation)
- Try [Dash](http://kapeli.com/dash)
- Try [OmniRef](https://www.omniref.com/)
- Sign up to use the [Suncoast Dev Slack](http://suncoast.io)
- Install the [better_errors gem](https://github.com/charliesome/better_errors) in your Pinterest application. Create an error to see how it works.
- Read about the [Rails logger](http://guides.rubyonrails.org/debugging_rails_applications.html) and implement some lines in your controller. Output an instance variable using the `.inspect` method to the log. Paste the section of your log file in a comment in this issue. In an issue comment direct me to where you have added the logger statements. (Yes, in this case you can check logger statements in).
- Read about using the [pry console debugger](https://github.com/nixme/pry-debugger) and try it in a controller action.

**Comment by cato-hga** [comment]
Started GET "/movies" for 127.0.0.1 at 2015-03-16 15:15:16 -0400
Processing by MoviesController#index as HTML
  User Load (0.3ms)  SELECT  "users".\* FROM "users" WHERE "users"."name" = $1 LIMIT 1  [["name", "John"]](0.5ms)  SELECT COUNT(_) FROM "movies"
How Many Movies: 3
  Movie Load (0.3ms)  SELECT "movies"._ FROM "movies"
#<ActiveRecord::Relation [#<Movie id: 78, name: "Investor Identity Director", rating: "7", created_at: "2015-03-13 01:46:34", updated_at: "2015-03-13 01:46:34", theater_id: nil, currentviewings: "[\"Sit mollitia velit. Non iusto et ipsa aut corpor...", avatar: "etmaximetempore.png">, #<Movie id: 79, name: "Dynamic Metrics Architect", rating: "3", created_at: "2015-03-13 01:46:36", updated_at: "2015-03-13 01:46:36", theater_id: nil, currentviewings: "[\"Ab et necessitatibus asperiores aut consequatur....", avatar: "doloremeaqueeius.png">, #<Movie id: 80, name: "National Usability Agent", rating: "7", created_at: "2015-03-13 01:46:39", updated_at: "2015-03-13 01:46:39", theater_id: nil, currentviewings: "[\"Iusto quia sint. Dolor et aut quam possimus veli...", avatar: "etoccaecaticonsequuntur.png">]>

**Comment by cato-hga** [comment]
I placed the logger statements inside my Movies Controller in the Index action. The statement says, "How Many Movies: "

**Comment by brianburridge** [comment]
Saw when you were at my desk. :+1:
