### ISSUE TITLE
Create a checklist for a new Rails app (group assignment)

### ISSUE THREAD

**Issue by brianburridge** [cato-hga/Assignments#50]
_This is assignment 49 and is due on Mar 11, 2015._
- Create a checklist of things to do to create a new Rails app, version control it in git, share it in GitHub and finally, get it running on Heroku.
- Use [Markdown](https://help.github.com/articles/markdown-basics/) to create the list. Put it in your _Assignments_ git repo and push it to GitHub.

**Comment by cato-hga** [comment]
https://github.com/cato-hga/Assignments/blob/master/assignment49.md

**Comment by brianburridge** [comment]
:+1:
