### ISSUE TITLE
Intro to JS and jQuery- in class

### ISSUE THREAD

**Issue by brianburridge** [cato-hga/Assignments#59]
_This is assignment 58 and is due on Mar 25, 2015._
- Read through this [JavaScript Basics](http://jqfundamentals.com/chapter/javascript-basics) and put some of the examples in your JS and ensure they run, show the proper output in the console and that you understand the basics.
- Note: Use `console.log` where the demo shows just `log`.
- Note: The _this_ explanation is a tricky thing in JavaScript. Don't get bogged down by it. jQuery will help with that.
- Check the two HTML pages and two JS pages we created in class (and perhaps a css if you used one).

**Comment by cato-hga** [comment]
https://github.com/cato-hga/Assignments/tree/master/assignment58

**Comment by brianburridge** [comment]
:+1:
