### ISSUE TITLE
Happy Birthday!

### ISSUE THREAD

**Issue by brianburridge** [cato-hga/Assignments#6]
_This assignment is due on Jan 28, 2015._
- Create a Ruby script to ask the user for their name and then wish them a Happy Birthday by name
- Add some comments to your code
- Put this code in a gist and paste the link from the gist in a comment of this issue
## Bonus
- Add another prompt for birthdate
- Show the birth date in parenthesis after the greeting
- Note: user must enter date in like: 2014/09/22 or 2014-09-22
- Change the output formatting to: Friday, April 1, 1974
- Capitalize the user's name

**Comment by cato-hga** [comment]
https://gist.github.com/cato-hga/525b56ba17840ac60cc0

**Comment by brianburridge** [comment]
:+1:
