### ISSUE TITLE
Creating Variables and Literals

### ISSUE THREAD

**Issue by brianburridge** [cato-hga/Assignments#7]
_This assignment is due on Jan 28, 2015._
- Create code for each comment in [this gist](https://gist.github.com/brianburridge/79de494772daf7976ea9)
- Run the code and paste the output into your issue as a comment for this assignment
- It should list all the proper class names and all class tests should result in 'true'
- Before you run it, can you guess what will happen with the constant code you've created?

**Comment by cato-hga** [comment]
https://gist.github.com/cato-hga/e52278e4e606065b8e17

**Comment by brianburridge** [comment]
@cato-hga there are a few problems with this code
1. it doesn't run for me. Throws a date error.
2. On line 43 you are creating an array, not a hash
3. Online 56 you are outputting a string with a values of "NAMES", not the constant NAMES.
4. Line 5, you are creating a String not a Date

**Comment by cato-hga** [comment]
Resending it now

**Comment by cato-hga** [comment]
https://gist.github.com/cato-hga/de8a1756399e6fe46a79

**Comment by cato-hga** [comment]
String
Date
Fixnum
Array
Array
Hash
true
true
true
true
true
true
String
Fixnum
Array
Hash
Symbol
ase7.rb:53: warning: already initialized constant NAME
ase7.rb:50: warning: previous definition of NAME was here

**Comment by brianburridge** [comment]
Everything looks good now except you aren't outputting the the constant at the end.

**Comment by cato-hga** [comment]
https://gist.github.com/cato-hga/de8a1756399e6fe46a79

**Comment by brianburridge** [comment]
:+1:
