### ISSUE TITLE
Working with Loops

### ISSUE THREAD

**Issue by brianburridge** [cato-hga/Assignments#8]
_This assignment is due on Jan 29, 2015._
- Request input of a number from the user.
- Iterate the number of times indicated by the input number
- Within the loop, print the number of the iteration
- Do this for each of these methods of looping: while, for i in rage, loop, until, .times with counter, until, range
- All should print from 1 to the number input by the user

**Comment by cato-hga** [comment]
I sent them in individual files on accident. Sorry

**Comment by brianburridge** [comment]
:+1:
